### ISSUE TITLE
Installer seem to be infect

### ISSUE THREAD

**Issue by ILPlais** [RRUZ/delphi-dev-shell-tools#20]
Hello,

It seem the installer is infect!

[VirusTotal return some results.](https://virustotal.com/file/370f4c99399e148112cebc4a00649f9e0e5ed3462a9b9ea1d1a733ccc99f8f4c/analysis/) And Windows Defender block the installation.

Is it a false positive or the installer is really infect?

**Comment by RRUZ** [comment]
Hi, this is a false positive off course,  The source code of the script installer is here  https://github.com/RRUZ/delphi-dev-shell-tools/blob/master/Installer.iss if you have any doubts you can build the shell extension and the installer using the repo.
